FROM ubuntu:20.04

WORKDIR /code

COPY .  /code

RUN apt-get update && apt-get install -y curl

# Install Node.js
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs

# Install Playwright and its dependencies
RUN npm i -g playwright
RUN npx playwright install-deps
